// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dst_existence_fusion_config.proto

#ifndef PROTOBUF_dst_5fexistence_5ffusion_5fconfig_2eproto__INCLUDED
#define PROTOBUF_dst_5fexistence_5ffusion_5fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace apollo {
namespace perception {
class CameraValidDist;
class CameraValidDistDefaultTypeInternal;
extern CameraValidDistDefaultTypeInternal _CameraValidDist_default_instance_;
class DstExistenceFusionConfig;
class DstExistenceFusionConfigDefaultTypeInternal;
extern DstExistenceFusionConfigDefaultTypeInternal _DstExistenceFusionConfig_default_instance_;
}  // namespace perception
}  // namespace apollo

namespace apollo {
namespace perception {

namespace protobuf_dst_5fexistence_5ffusion_5fconfig_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_dst_5fexistence_5ffusion_5fconfig_2eproto

// ===================================================================

class CameraValidDist : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.CameraValidDist) */ {
 public:
  CameraValidDist();
  virtual ~CameraValidDist();

  CameraValidDist(const CameraValidDist& from);

  inline CameraValidDist& operator=(const CameraValidDist& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraValidDist& default_instance();

  static inline const CameraValidDist* internal_default_instance() {
    return reinterpret_cast<const CameraValidDist*>(
               &_CameraValidDist_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CameraValidDist* other);

  // implements Message ----------------------------------------------

  inline CameraValidDist* New() const PROTOBUF_FINAL { return New(NULL); }

  CameraValidDist* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CameraValidDist& from);
  void MergeFrom(const CameraValidDist& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CameraValidDist* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string camera_name = 1 [default = ""];
  bool has_camera_name() const;
  void clear_camera_name();
  static const int kCameraNameFieldNumber = 1;
  const ::std::string& camera_name() const;
  void set_camera_name(const ::std::string& value);
  #if LANG_CXX11
  void set_camera_name(::std::string&& value);
  #endif
  void set_camera_name(const char* value);
  void set_camera_name(const char* value, size_t size);
  ::std::string* mutable_camera_name();
  ::std::string* release_camera_name();
  void set_allocated_camera_name(::std::string* camera_name);

  // optional double valid_dist = 2 [default = 0];
  bool has_valid_dist() const;
  void clear_valid_dist();
  static const int kValidDistFieldNumber = 2;
  double valid_dist() const;
  void set_valid_dist(double value);

  // @@protoc_insertion_point(class_scope:apollo.perception.CameraValidDist)
 private:
  void set_has_camera_name();
  void clear_has_camera_name();
  void set_has_valid_dist();
  void clear_has_valid_dist();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr camera_name_;
  double valid_dist_;
  friend struct protobuf_dst_5fexistence_5ffusion_5fconfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DstExistenceFusionConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.perception.DstExistenceFusionConfig) */ {
 public:
  DstExistenceFusionConfig();
  virtual ~DstExistenceFusionConfig();

  DstExistenceFusionConfig(const DstExistenceFusionConfig& from);

  inline DstExistenceFusionConfig& operator=(const DstExistenceFusionConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DstExistenceFusionConfig& default_instance();

  static inline const DstExistenceFusionConfig* internal_default_instance() {
    return reinterpret_cast<const DstExistenceFusionConfig*>(
               &_DstExistenceFusionConfig_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(DstExistenceFusionConfig* other);

  // implements Message ----------------------------------------------

  inline DstExistenceFusionConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  DstExistenceFusionConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DstExistenceFusionConfig& from);
  void MergeFrom(const DstExistenceFusionConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DstExistenceFusionConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.CameraValidDist camera_valid_dist = 2;
  int camera_valid_dist_size() const;
  void clear_camera_valid_dist();
  static const int kCameraValidDistFieldNumber = 2;
  const ::apollo::perception::CameraValidDist& camera_valid_dist(int index) const;
  ::apollo::perception::CameraValidDist* mutable_camera_valid_dist(int index);
  ::apollo::perception::CameraValidDist* add_camera_valid_dist();
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::CameraValidDist >*
      mutable_camera_valid_dist();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::CameraValidDist >&
      camera_valid_dist() const;

  // optional double track_object_max_match_distance = 1 [default = 4];
  bool has_track_object_max_match_distance() const;
  void clear_track_object_max_match_distance();
  static const int kTrackObjectMaxMatchDistanceFieldNumber = 1;
  double track_object_max_match_distance() const;
  void set_track_object_max_match_distance(double value);

  // @@protoc_insertion_point(class_scope:apollo.perception.DstExistenceFusionConfig)
 private:
  void set_has_track_object_max_match_distance();
  void clear_has_track_object_max_match_distance();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::CameraValidDist > camera_valid_dist_;
  double track_object_max_match_distance_;
  friend struct protobuf_dst_5fexistence_5ffusion_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CameraValidDist

// optional string camera_name = 1 [default = ""];
inline bool CameraValidDist::has_camera_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CameraValidDist::set_has_camera_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CameraValidDist::clear_has_camera_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CameraValidDist::clear_camera_name() {
  camera_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_camera_name();
}
inline const ::std::string& CameraValidDist::camera_name() const {
  // @@protoc_insertion_point(field_get:apollo.perception.CameraValidDist.camera_name)
  return camera_name_.GetNoArena();
}
inline void CameraValidDist::set_camera_name(const ::std::string& value) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.perception.CameraValidDist.camera_name)
}
#if LANG_CXX11
inline void CameraValidDist::set_camera_name(::std::string&& value) {
  set_has_camera_name();
  camera_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.perception.CameraValidDist.camera_name)
}
#endif
inline void CameraValidDist::set_camera_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.perception.CameraValidDist.camera_name)
}
inline void CameraValidDist::set_camera_name(const char* value, size_t size) {
  set_has_camera_name();
  camera_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.CameraValidDist.camera_name)
}
inline ::std::string* CameraValidDist::mutable_camera_name() {
  set_has_camera_name();
  // @@protoc_insertion_point(field_mutable:apollo.perception.CameraValidDist.camera_name)
  return camera_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CameraValidDist::release_camera_name() {
  // @@protoc_insertion_point(field_release:apollo.perception.CameraValidDist.camera_name)
  clear_has_camera_name();
  return camera_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CameraValidDist::set_allocated_camera_name(::std::string* camera_name) {
  if (camera_name != NULL) {
    set_has_camera_name();
  } else {
    clear_has_camera_name();
  }
  camera_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.CameraValidDist.camera_name)
}

// optional double valid_dist = 2 [default = 0];
inline bool CameraValidDist::has_valid_dist() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CameraValidDist::set_has_valid_dist() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CameraValidDist::clear_has_valid_dist() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CameraValidDist::clear_valid_dist() {
  valid_dist_ = 0;
  clear_has_valid_dist();
}
inline double CameraValidDist::valid_dist() const {
  // @@protoc_insertion_point(field_get:apollo.perception.CameraValidDist.valid_dist)
  return valid_dist_;
}
inline void CameraValidDist::set_valid_dist(double value) {
  set_has_valid_dist();
  valid_dist_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.CameraValidDist.valid_dist)
}

// -------------------------------------------------------------------

// DstExistenceFusionConfig

// optional double track_object_max_match_distance = 1 [default = 4];
inline bool DstExistenceFusionConfig::has_track_object_max_match_distance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DstExistenceFusionConfig::set_has_track_object_max_match_distance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DstExistenceFusionConfig::clear_has_track_object_max_match_distance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DstExistenceFusionConfig::clear_track_object_max_match_distance() {
  track_object_max_match_distance_ = 4;
  clear_has_track_object_max_match_distance();
}
inline double DstExistenceFusionConfig::track_object_max_match_distance() const {
  // @@protoc_insertion_point(field_get:apollo.perception.DstExistenceFusionConfig.track_object_max_match_distance)
  return track_object_max_match_distance_;
}
inline void DstExistenceFusionConfig::set_track_object_max_match_distance(double value) {
  set_has_track_object_max_match_distance();
  track_object_max_match_distance_ = value;
  // @@protoc_insertion_point(field_set:apollo.perception.DstExistenceFusionConfig.track_object_max_match_distance)
}

// repeated .apollo.perception.CameraValidDist camera_valid_dist = 2;
inline int DstExistenceFusionConfig::camera_valid_dist_size() const {
  return camera_valid_dist_.size();
}
inline void DstExistenceFusionConfig::clear_camera_valid_dist() {
  camera_valid_dist_.Clear();
}
inline const ::apollo::perception::CameraValidDist& DstExistenceFusionConfig::camera_valid_dist(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.DstExistenceFusionConfig.camera_valid_dist)
  return camera_valid_dist_.Get(index);
}
inline ::apollo::perception::CameraValidDist* DstExistenceFusionConfig::mutable_camera_valid_dist(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.DstExistenceFusionConfig.camera_valid_dist)
  return camera_valid_dist_.Mutable(index);
}
inline ::apollo::perception::CameraValidDist* DstExistenceFusionConfig::add_camera_valid_dist() {
  // @@protoc_insertion_point(field_add:apollo.perception.DstExistenceFusionConfig.camera_valid_dist)
  return camera_valid_dist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::CameraValidDist >*
DstExistenceFusionConfig::mutable_camera_valid_dist() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.DstExistenceFusionConfig.camera_valid_dist)
  return &camera_valid_dist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::CameraValidDist >&
DstExistenceFusionConfig::camera_valid_dist() const {
  // @@protoc_insertion_point(field_list:apollo.perception.DstExistenceFusionConfig.camera_valid_dist)
  return camera_valid_dist_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dst_5fexistence_5ffusion_5fconfig_2eproto__INCLUDED
