// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbf_tracker_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pbf_tracker_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace perception {
namespace fusion {
class PbfTrackerConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<PbfTrackerConfig> {
} _PbfTrackerConfig_default_instance_;

namespace protobuf_pbf_5ftracker_5fconfig_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbfTrackerConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbfTrackerConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbfTrackerConfig, type_fusion_method_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbfTrackerConfig, motion_fusion_method_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbfTrackerConfig, shape_fusion_method_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbfTrackerConfig, existence_fusion_method_),
  0,
  1,
  2,
  3,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 9, sizeof(PbfTrackerConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_PbfTrackerConfig_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "pbf_tracker_config.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _PbfTrackerConfig_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  PbfTrackerConfig::_default_type_fusion_method_.Shutdown();
  PbfTrackerConfig::_default_motion_fusion_method_.Shutdown();
  PbfTrackerConfig::_default_shape_fusion_method_.Shutdown();
  PbfTrackerConfig::_default_existence_fusion_method_.Shutdown();
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  PbfTrackerConfig::_default_type_fusion_method_.DefaultConstruct();
  *PbfTrackerConfig::_default_type_fusion_method_.get_mutable() = ::std::string("DstTypeFusion", 13);
  PbfTrackerConfig::_default_motion_fusion_method_.DefaultConstruct();
  *PbfTrackerConfig::_default_motion_fusion_method_.get_mutable() = ::std::string("KalmanMotionFusion", 18);
  PbfTrackerConfig::_default_shape_fusion_method_.DefaultConstruct();
  *PbfTrackerConfig::_default_shape_fusion_method_.get_mutable() = ::std::string("PbfShapeFusion", 14);
  PbfTrackerConfig::_default_existence_fusion_method_.DefaultConstruct();
  *PbfTrackerConfig::_default_existence_fusion_method_.get_mutable() = ::std::string("DstExistenceFusion", 18);
  _PbfTrackerConfig_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\030pbf_tracker_config.proto\022\030apollo.perce"
      "ption.fusion\"\321\001\n\020PbfTrackerConfig\022)\n\022typ"
      "e_fusion_method\030\001 \001(\t:\rDstTypeFusion\0220\n\024"
      "motion_fusion_method\030\002 \001(\t:\022KalmanMotion"
      "Fusion\022+\n\023shape_fusion_method\030\003 \001(\t:\016Pbf"
      "ShapeFusion\0223\n\027existence_fusion_method\030\004"
      " \001(\t:\022DstExistenceFusion"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 264);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pbf_tracker_config.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_pbf_5ftracker_5fconfig_2eproto


// ===================================================================

::google::protobuf::internal::ExplicitlyConstructed< ::std::string> PbfTrackerConfig::_default_type_fusion_method_;
::google::protobuf::internal::ExplicitlyConstructed< ::std::string> PbfTrackerConfig::_default_motion_fusion_method_;
::google::protobuf::internal::ExplicitlyConstructed< ::std::string> PbfTrackerConfig::_default_shape_fusion_method_;
::google::protobuf::internal::ExplicitlyConstructed< ::std::string> PbfTrackerConfig::_default_existence_fusion_method_;
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PbfTrackerConfig::kTypeFusionMethodFieldNumber;
const int PbfTrackerConfig::kMotionFusionMethodFieldNumber;
const int PbfTrackerConfig::kShapeFusionMethodFieldNumber;
const int PbfTrackerConfig::kExistenceFusionMethodFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PbfTrackerConfig::PbfTrackerConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_pbf_5ftracker_5fconfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.perception.fusion.PbfTrackerConfig)
}
PbfTrackerConfig::PbfTrackerConfig(const PbfTrackerConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_type_fusion_method_.get());
  if (from.has_type_fusion_method()) {
    type_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_type_fusion_method_.get(), from.type_fusion_method_);
  }
  motion_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_motion_fusion_method_.get());
  if (from.has_motion_fusion_method()) {
    motion_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_motion_fusion_method_.get(), from.motion_fusion_method_);
  }
  shape_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_shape_fusion_method_.get());
  if (from.has_shape_fusion_method()) {
    shape_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_shape_fusion_method_.get(), from.shape_fusion_method_);
  }
  existence_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_existence_fusion_method_.get());
  if (from.has_existence_fusion_method()) {
    existence_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_existence_fusion_method_.get(), from.existence_fusion_method_);
  }
  // @@protoc_insertion_point(copy_constructor:apollo.perception.fusion.PbfTrackerConfig)
}

void PbfTrackerConfig::SharedCtor() {
  _cached_size_ = 0;
  type_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_type_fusion_method_.get());
  motion_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_motion_fusion_method_.get());
  shape_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_shape_fusion_method_.get());
  existence_fusion_method_.UnsafeSetDefault(&PbfTrackerConfig::_default_existence_fusion_method_.get());
}

PbfTrackerConfig::~PbfTrackerConfig() {
  // @@protoc_insertion_point(destructor:apollo.perception.fusion.PbfTrackerConfig)
  SharedDtor();
}

void PbfTrackerConfig::SharedDtor() {
  type_fusion_method_.DestroyNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get());
  motion_fusion_method_.DestroyNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get());
  shape_fusion_method_.DestroyNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get());
  existence_fusion_method_.DestroyNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get());
}

void PbfTrackerConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbfTrackerConfig::descriptor() {
  protobuf_pbf_5ftracker_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_pbf_5ftracker_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PbfTrackerConfig& PbfTrackerConfig::default_instance() {
  protobuf_pbf_5ftracker_5fconfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

PbfTrackerConfig* PbfTrackerConfig::New(::google::protobuf::Arena* arena) const {
  PbfTrackerConfig* n = new PbfTrackerConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PbfTrackerConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.perception.fusion.PbfTrackerConfig)
  if (_has_bits_[0 / 32] & 15u) {
    if (has_type_fusion_method()) {
      GOOGLE_DCHECK(!type_fusion_method_.IsDefault(&PbfTrackerConfig::_default_type_fusion_method_.get()));
      (*type_fusion_method_.UnsafeRawStringPointer())->assign(*&PbfTrackerConfig::_default_type_fusion_method_.get());
    }
    if (has_motion_fusion_method()) {
      GOOGLE_DCHECK(!motion_fusion_method_.IsDefault(&PbfTrackerConfig::_default_motion_fusion_method_.get()));
      (*motion_fusion_method_.UnsafeRawStringPointer())->assign(*&PbfTrackerConfig::_default_motion_fusion_method_.get());
    }
    if (has_shape_fusion_method()) {
      GOOGLE_DCHECK(!shape_fusion_method_.IsDefault(&PbfTrackerConfig::_default_shape_fusion_method_.get()));
      (*shape_fusion_method_.UnsafeRawStringPointer())->assign(*&PbfTrackerConfig::_default_shape_fusion_method_.get());
    }
    if (has_existence_fusion_method()) {
      GOOGLE_DCHECK(!existence_fusion_method_.IsDefault(&PbfTrackerConfig::_default_existence_fusion_method_.get()));
      (*existence_fusion_method_.UnsafeRawStringPointer())->assign(*&PbfTrackerConfig::_default_existence_fusion_method_.get());
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool PbfTrackerConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.perception.fusion.PbfTrackerConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string type_fusion_method = 1 [default = "DstTypeFusion"];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type_fusion_method()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type_fusion_method().data(), this->type_fusion_method().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.perception.fusion.PbfTrackerConfig.type_fusion_method");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string motion_fusion_method = 2 [default = "KalmanMotionFusion"];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_motion_fusion_method()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->motion_fusion_method().data(), this->motion_fusion_method().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string shape_fusion_method = 3 [default = "PbfShapeFusion"];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_shape_fusion_method()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->shape_fusion_method().data(), this->shape_fusion_method().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string existence_fusion_method = 4 [default = "DstExistenceFusion"];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_existence_fusion_method()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->existence_fusion_method().data(), this->existence_fusion_method().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.perception.fusion.PbfTrackerConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.perception.fusion.PbfTrackerConfig)
  return false;
#undef DO_
}

void PbfTrackerConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.perception.fusion.PbfTrackerConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string type_fusion_method = 1 [default = "DstTypeFusion"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type_fusion_method().data(), this->type_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.type_fusion_method");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type_fusion_method(), output);
  }

  // optional string motion_fusion_method = 2 [default = "KalmanMotionFusion"];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->motion_fusion_method().data(), this->motion_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->motion_fusion_method(), output);
  }

  // optional string shape_fusion_method = 3 [default = "PbfShapeFusion"];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->shape_fusion_method().data(), this->shape_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->shape_fusion_method(), output);
  }

  // optional string existence_fusion_method = 4 [default = "DstExistenceFusion"];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->existence_fusion_method().data(), this->existence_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->existence_fusion_method(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.perception.fusion.PbfTrackerConfig)
}

::google::protobuf::uint8* PbfTrackerConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.perception.fusion.PbfTrackerConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string type_fusion_method = 1 [default = "DstTypeFusion"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type_fusion_method().data(), this->type_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.type_fusion_method");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type_fusion_method(), target);
  }

  // optional string motion_fusion_method = 2 [default = "KalmanMotionFusion"];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->motion_fusion_method().data(), this->motion_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->motion_fusion_method(), target);
  }

  // optional string shape_fusion_method = 3 [default = "PbfShapeFusion"];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->shape_fusion_method().data(), this->shape_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->shape_fusion_method(), target);
  }

  // optional string existence_fusion_method = 4 [default = "DstExistenceFusion"];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->existence_fusion_method().data(), this->existence_fusion_method().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->existence_fusion_method(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.perception.fusion.PbfTrackerConfig)
  return target;
}

size_t PbfTrackerConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.perception.fusion.PbfTrackerConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional string type_fusion_method = 1 [default = "DstTypeFusion"];
    if (has_type_fusion_method()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type_fusion_method());
    }

    // optional string motion_fusion_method = 2 [default = "KalmanMotionFusion"];
    if (has_motion_fusion_method()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->motion_fusion_method());
    }

    // optional string shape_fusion_method = 3 [default = "PbfShapeFusion"];
    if (has_shape_fusion_method()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->shape_fusion_method());
    }

    // optional string existence_fusion_method = 4 [default = "DstExistenceFusion"];
    if (has_existence_fusion_method()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->existence_fusion_method());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbfTrackerConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.perception.fusion.PbfTrackerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const PbfTrackerConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PbfTrackerConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.perception.fusion.PbfTrackerConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.perception.fusion.PbfTrackerConfig)
    MergeFrom(*source);
  }
}

void PbfTrackerConfig::MergeFrom(const PbfTrackerConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.perception.fusion.PbfTrackerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_type_fusion_method();
      type_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_type_fusion_method_.get(), from.type_fusion_method_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_motion_fusion_method();
      motion_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_motion_fusion_method_.get(), from.motion_fusion_method_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_shape_fusion_method();
      shape_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_shape_fusion_method_.get(), from.shape_fusion_method_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_existence_fusion_method();
      existence_fusion_method_.AssignWithDefault(&PbfTrackerConfig::_default_existence_fusion_method_.get(), from.existence_fusion_method_);
    }
  }
}

void PbfTrackerConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.perception.fusion.PbfTrackerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbfTrackerConfig::CopyFrom(const PbfTrackerConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.perception.fusion.PbfTrackerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbfTrackerConfig::IsInitialized() const {
  return true;
}

void PbfTrackerConfig::Swap(PbfTrackerConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PbfTrackerConfig::InternalSwap(PbfTrackerConfig* other) {
  type_fusion_method_.Swap(&other->type_fusion_method_);
  motion_fusion_method_.Swap(&other->motion_fusion_method_);
  shape_fusion_method_.Swap(&other->shape_fusion_method_);
  existence_fusion_method_.Swap(&other->existence_fusion_method_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PbfTrackerConfig::GetMetadata() const {
  protobuf_pbf_5ftracker_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_pbf_5ftracker_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PbfTrackerConfig

// optional string type_fusion_method = 1 [default = "DstTypeFusion"];
bool PbfTrackerConfig::has_type_fusion_method() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PbfTrackerConfig::set_has_type_fusion_method() {
  _has_bits_[0] |= 0x00000001u;
}
void PbfTrackerConfig::clear_has_type_fusion_method() {
  _has_bits_[0] &= ~0x00000001u;
}
void PbfTrackerConfig::clear_type_fusion_method() {
  type_fusion_method_.ClearToDefaultNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get());
  clear_has_type_fusion_method();
}
const ::std::string& PbfTrackerConfig::type_fusion_method() const {
  // @@protoc_insertion_point(field_get:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
  return type_fusion_method_.GetNoArena();
}
void PbfTrackerConfig::set_type_fusion_method(const ::std::string& value) {
  set_has_type_fusion_method();
  type_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get(), value);
  // @@protoc_insertion_point(field_set:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
}
#if LANG_CXX11
void PbfTrackerConfig::set_type_fusion_method(::std::string&& value) {
  set_has_type_fusion_method();
  type_fusion_method_.SetNoArena(
    &PbfTrackerConfig::_default_type_fusion_method_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
}
#endif
void PbfTrackerConfig::set_type_fusion_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_type_fusion_method();
  type_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
}
void PbfTrackerConfig::set_type_fusion_method(const char* value, size_t size) {
  set_has_type_fusion_method();
  type_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
}
::std::string* PbfTrackerConfig::mutable_type_fusion_method() {
  set_has_type_fusion_method();
  // @@protoc_insertion_point(field_mutable:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
  return type_fusion_method_.MutableNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get());
}
::std::string* PbfTrackerConfig::release_type_fusion_method() {
  // @@protoc_insertion_point(field_release:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
  clear_has_type_fusion_method();
  return type_fusion_method_.ReleaseNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get());
}
void PbfTrackerConfig::set_allocated_type_fusion_method(::std::string* type_fusion_method) {
  if (type_fusion_method != NULL) {
    set_has_type_fusion_method();
  } else {
    clear_has_type_fusion_method();
  }
  type_fusion_method_.SetAllocatedNoArena(&PbfTrackerConfig::_default_type_fusion_method_.get(), type_fusion_method);
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.fusion.PbfTrackerConfig.type_fusion_method)
}

// optional string motion_fusion_method = 2 [default = "KalmanMotionFusion"];
bool PbfTrackerConfig::has_motion_fusion_method() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void PbfTrackerConfig::set_has_motion_fusion_method() {
  _has_bits_[0] |= 0x00000002u;
}
void PbfTrackerConfig::clear_has_motion_fusion_method() {
  _has_bits_[0] &= ~0x00000002u;
}
void PbfTrackerConfig::clear_motion_fusion_method() {
  motion_fusion_method_.ClearToDefaultNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get());
  clear_has_motion_fusion_method();
}
const ::std::string& PbfTrackerConfig::motion_fusion_method() const {
  // @@protoc_insertion_point(field_get:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
  return motion_fusion_method_.GetNoArena();
}
void PbfTrackerConfig::set_motion_fusion_method(const ::std::string& value) {
  set_has_motion_fusion_method();
  motion_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get(), value);
  // @@protoc_insertion_point(field_set:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
}
#if LANG_CXX11
void PbfTrackerConfig::set_motion_fusion_method(::std::string&& value) {
  set_has_motion_fusion_method();
  motion_fusion_method_.SetNoArena(
    &PbfTrackerConfig::_default_motion_fusion_method_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
}
#endif
void PbfTrackerConfig::set_motion_fusion_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_motion_fusion_method();
  motion_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
}
void PbfTrackerConfig::set_motion_fusion_method(const char* value, size_t size) {
  set_has_motion_fusion_method();
  motion_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
}
::std::string* PbfTrackerConfig::mutable_motion_fusion_method() {
  set_has_motion_fusion_method();
  // @@protoc_insertion_point(field_mutable:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
  return motion_fusion_method_.MutableNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get());
}
::std::string* PbfTrackerConfig::release_motion_fusion_method() {
  // @@protoc_insertion_point(field_release:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
  clear_has_motion_fusion_method();
  return motion_fusion_method_.ReleaseNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get());
}
void PbfTrackerConfig::set_allocated_motion_fusion_method(::std::string* motion_fusion_method) {
  if (motion_fusion_method != NULL) {
    set_has_motion_fusion_method();
  } else {
    clear_has_motion_fusion_method();
  }
  motion_fusion_method_.SetAllocatedNoArena(&PbfTrackerConfig::_default_motion_fusion_method_.get(), motion_fusion_method);
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.fusion.PbfTrackerConfig.motion_fusion_method)
}

// optional string shape_fusion_method = 3 [default = "PbfShapeFusion"];
bool PbfTrackerConfig::has_shape_fusion_method() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void PbfTrackerConfig::set_has_shape_fusion_method() {
  _has_bits_[0] |= 0x00000004u;
}
void PbfTrackerConfig::clear_has_shape_fusion_method() {
  _has_bits_[0] &= ~0x00000004u;
}
void PbfTrackerConfig::clear_shape_fusion_method() {
  shape_fusion_method_.ClearToDefaultNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get());
  clear_has_shape_fusion_method();
}
const ::std::string& PbfTrackerConfig::shape_fusion_method() const {
  // @@protoc_insertion_point(field_get:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
  return shape_fusion_method_.GetNoArena();
}
void PbfTrackerConfig::set_shape_fusion_method(const ::std::string& value) {
  set_has_shape_fusion_method();
  shape_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get(), value);
  // @@protoc_insertion_point(field_set:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
}
#if LANG_CXX11
void PbfTrackerConfig::set_shape_fusion_method(::std::string&& value) {
  set_has_shape_fusion_method();
  shape_fusion_method_.SetNoArena(
    &PbfTrackerConfig::_default_shape_fusion_method_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
}
#endif
void PbfTrackerConfig::set_shape_fusion_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_shape_fusion_method();
  shape_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
}
void PbfTrackerConfig::set_shape_fusion_method(const char* value, size_t size) {
  set_has_shape_fusion_method();
  shape_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
}
::std::string* PbfTrackerConfig::mutable_shape_fusion_method() {
  set_has_shape_fusion_method();
  // @@protoc_insertion_point(field_mutable:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
  return shape_fusion_method_.MutableNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get());
}
::std::string* PbfTrackerConfig::release_shape_fusion_method() {
  // @@protoc_insertion_point(field_release:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
  clear_has_shape_fusion_method();
  return shape_fusion_method_.ReleaseNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get());
}
void PbfTrackerConfig::set_allocated_shape_fusion_method(::std::string* shape_fusion_method) {
  if (shape_fusion_method != NULL) {
    set_has_shape_fusion_method();
  } else {
    clear_has_shape_fusion_method();
  }
  shape_fusion_method_.SetAllocatedNoArena(&PbfTrackerConfig::_default_shape_fusion_method_.get(), shape_fusion_method);
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.fusion.PbfTrackerConfig.shape_fusion_method)
}

// optional string existence_fusion_method = 4 [default = "DstExistenceFusion"];
bool PbfTrackerConfig::has_existence_fusion_method() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void PbfTrackerConfig::set_has_existence_fusion_method() {
  _has_bits_[0] |= 0x00000008u;
}
void PbfTrackerConfig::clear_has_existence_fusion_method() {
  _has_bits_[0] &= ~0x00000008u;
}
void PbfTrackerConfig::clear_existence_fusion_method() {
  existence_fusion_method_.ClearToDefaultNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get());
  clear_has_existence_fusion_method();
}
const ::std::string& PbfTrackerConfig::existence_fusion_method() const {
  // @@protoc_insertion_point(field_get:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
  return existence_fusion_method_.GetNoArena();
}
void PbfTrackerConfig::set_existence_fusion_method(const ::std::string& value) {
  set_has_existence_fusion_method();
  existence_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get(), value);
  // @@protoc_insertion_point(field_set:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
}
#if LANG_CXX11
void PbfTrackerConfig::set_existence_fusion_method(::std::string&& value) {
  set_has_existence_fusion_method();
  existence_fusion_method_.SetNoArena(
    &PbfTrackerConfig::_default_existence_fusion_method_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
}
#endif
void PbfTrackerConfig::set_existence_fusion_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_existence_fusion_method();
  existence_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
}
void PbfTrackerConfig::set_existence_fusion_method(const char* value, size_t size) {
  set_has_existence_fusion_method();
  existence_fusion_method_.SetNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
}
::std::string* PbfTrackerConfig::mutable_existence_fusion_method() {
  set_has_existence_fusion_method();
  // @@protoc_insertion_point(field_mutable:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
  return existence_fusion_method_.MutableNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get());
}
::std::string* PbfTrackerConfig::release_existence_fusion_method() {
  // @@protoc_insertion_point(field_release:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
  clear_has_existence_fusion_method();
  return existence_fusion_method_.ReleaseNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get());
}
void PbfTrackerConfig::set_allocated_existence_fusion_method(::std::string* existence_fusion_method) {
  if (existence_fusion_method != NULL) {
    set_has_existence_fusion_method();
  } else {
    clear_has_existence_fusion_method();
  }
  existence_fusion_method_.SetAllocatedNoArena(&PbfTrackerConfig::_default_existence_fusion_method_.get(), existence_fusion_method);
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.fusion.PbfTrackerConfig.existence_fusion_method)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace fusion
}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
